package com.buberdinner.NotificationService.infrastructure.clients;

import com.buberdinner.NotificationService.domain.exception.NotificationDeliveryException;
import com.buberdinner.NotificationService.domain.model.Notification;
import com.buberdinner.NotificationService.infrastructure.config.EmailProperties;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j; // ADD THIS IMPORT
import org.springframework.mail.MailException;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Component;

@Slf4j // ADD THIS ANNOTATION
@Component
@RequiredArgsConstructor
public class EmailNotificationSender {

    private final JavaMailSender javaMailSender;
    private final EmailProperties emailProperties;

    public void sendEmail(Notification notification) {
        String recipient = notification.getEmail(); // Getters are generated by @Value on Notification
        String subject = notification.getSubject();
        String content = notification.getDescription();

        try {
            SimpleMailMessage message = new SimpleMailMessage();
            message.setFrom(emailProperties.getFrom());
            message.setTo(recipient);
            message.setSubject("BuberDinner - " + subject);
            message.setText(content);

            javaMailSender.send(message);
            log.info("Email sent successfully to {} for notification ID: {}", recipient, notification.getId()); // Use getter
        } catch (MailException e) {
            log.error("Failed to send email to {} for notification ID {}: {}", recipient, notification.getId(), e.getMessage(), e); // Use getter
            throw new NotificationDeliveryException("Email delivery failed to " + recipient, e);
        }
    }
}