package com.buberdinner.NotificationService.infrastructure.adapter.gateway;

import com.buberdinner.NotificationService.application.ports.output.NotificationSenderPort;
import com.buberdinner.NotificationService.domain.exception.NotificationDeliveryException;
import com.buberdinner.NotificationService.domain.model.Notification;
import com.buberdinner.NotificationService.domain.model.NotificationChannel; // ADD THIS IMPORT
import com.buberdinner.NotificationService.infrastructure.clients.EmailNotificationSender;
import com.buberdinner.NotificationService.infrastructure.clients.PushNotificationSender;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j; // ADD THIS IMPORT
import org.springframework.stereotype.Component;

@Component
@RequiredArgsConstructor
@Slf4j // ADD THIS ANNOTATION
public class NotificationSenderAdapter implements NotificationSenderPort {

    private final EmailNotificationSender emailSender;
    private final PushNotificationSender pushSender;

    @Override
    public void sendNotification(Notification notification) {
        if (notification == null) {
            log.warn("Attempted to send a null notification.");
            return;
        }

        try {
            // Qualify enum values with NotificationChannel.
            switch (notification.getChannel()) { // Getters are generated by @Value on Notification
                case EMAIL: // Correct: NotificationChannel.EMAIL is implicitly used here
                    emailSender.sendEmail(notification);
                    break;
                case PUSH: // Correct: NotificationChannel.PUSH is implicitly used here
                    pushSender.sendPushNotification(notification);
                    break;
                case SMS:
                    log.warn("SMS channel is not yet implemented for notification ID: {}", notification.getId());
                    throw new UnsupportedOperationException("SMS channel not yet implemented.");
                case IN_APP:
                    log.warn("In-App channel is not yet implemented for notification ID: {}", notification.getId());
                    throw new UnsupportedOperationException("In-App channel not yet implemented.");
                default:
                    log.error("Unsupported notification channel for notification ID {}: {}", notification.getId(), notification.getChannel());
                    throw new IllegalArgumentException("Unsupported notification channel: " + notification.getChannel());
            }
        } catch (NotificationDeliveryException e) {
            throw e; // Re-throw specific delivery exceptions
        } catch (Exception e) {
            log.error("An unexpected error occurred while trying to send notification {} (ID: {}): {}",
                    notification.getSubject(), notification.getId(), e.getMessage(), e); // Use getters
            throw new NotificationDeliveryException("Unexpected error during notification sending for ID " + notification.getId(), e);
        }
    }
}