package com.buberdinner.NotificationService.infrastructure.entrypoints.rest;

import com.buberdinner.NotificationService.application.ports.input.NotificationInputPort;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import lombok.Data; // ADD THIS IMPORT
import lombok.NoArgsConstructor; // ADD THIS IMPORT
import lombok.AllArgsConstructor; // ADD THIS IMPORT

@RestController
@RequestMapping("/api/notifications")
@RequiredArgsConstructor
public class NotificationController {

    private final NotificationInputPort notificationInputPort;

    @Data // ADD THIS ANNOTATION to generate getters (and setters, etc.)
    @NoArgsConstructor // ADD THIS ANNOTATION
    @AllArgsConstructor // ADD THIS ANNOTATION
    public static class SendNotificationRequest {
        private String userId;
        private String email;
        private String subject;
        private String description;
        private String channel; // e.g., "EMAIL", "PUSH"
    }

    @PostMapping("/send-immediate")
    public ResponseEntity<String> sendImmediate(@RequestBody SendNotificationRequest request) {
        try {
            // Getters are now generated by @Data
            notificationInputPort.sendImmediateNotification(
                    request.getUserId(),
                    request.getEmail(),
                    request.getSubject(),
                    request.getDescription(),
                    request.getChannel()
            );
            return ResponseEntity.ok("Notification sent successfully (or queued).");
        } catch (IllegalArgumentException e) {
            return ResponseEntity.badRequest().body(e.getMessage());
        } catch (Exception e) {
            return ResponseEntity.internalServerError().body("Failed to send notification: " + e.getMessage());
        }
    }
}